In [2]:

import os
os.chdir('/Users/prabhakarchettiar/python2020')
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
os.getcwd()

'/Users/prabhakarchettiar/python2020'

In [9]:
dataset1 = pd.read_excel('sal1.xls')
dataset2 = pd.read_excel('sal2.xls')
dataset3 = pd.read_excel('sal3.xls')
dataset4 = pd.read_excel('sal4.xls')
dataset5 = pd.read_excel('sal5.xls')

In [10]:
dataset1.isnull().sum()

Experience    0
Salary        0
dtype: int64

In [11]:
sal1=dataset1.iloc[:].values
sal2=dataset2.iloc[:].values
sal3=dataset3.iloc[:].values
sal4=dataset4.iloc[:].values
sal5=dataset5.iloc[:].values

In [12]:
sal1

array([[    5, 10000],
       [    7, 12000],
       [    9, 14000],
       [   10, 16000],
       [   12, 20000],
       [   14, 22000],
       [   15, 23000],
       [   16, 27000],
       [   18, 30000],
       [   21, 40000]])

In [13]:
x1=dataset1.iloc[:,0:1].values
y1 = dataset1.iloc[:,1].values

x2=dataset2.iloc[:,0:1].values
y2 = dataset2.iloc[:,1].values

x3=dataset3.iloc[:,0:1].values
y3 = dataset3.iloc[:,1].values

x4=dataset4.iloc[:,0:1].values
y4 = dataset4.iloc[:,1].values

x5=dataset5.iloc[:,0:1].values
y5 = dataset5.iloc[:,1].values

In [14]:
x1

array([[ 5],
       [ 7],
       [ 9],
       [10],
       [12],
       [14],
       [15],
       [16],
       [18],
       [21]])

In [15]:
y1

array([10000, 12000, 14000, 16000, 20000, 22000, 23000, 27000, 30000,
       40000])

In [17]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1,test_size=0.3,
                                                   random_state=10)


from sklearn.model_selection import train_test_split
x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y2,test_size=0.3,
                                                   random_state=10)

from sklearn.model_selection import train_test_split
x3_train, x3_test, y3_train, y3_test = train_test_split(x3,y3,test_size=0.3,
                                                   random_state=10)

from sklearn.model_selection import train_test_split
x4_train, x4_test, y4_train, y4_test = train_test_split(x4,y4,test_size=0.3,
                                                   random_state=10)

from sklearn.model_selection import train_test_split
x5_train, x5_test, y5_train, y5_test = train_test_split(x5,y5,test_size=0.3,
                                                   random_state=10)

In [20]:

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x1_train, y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
regressor.coef_

array([1813.86292835])

In [22]:
regressor.intercept_

-1141.744548286606

In [23]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x2_train, y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
regressor.coef_

array([-1778.81619938])

In [25]:
regressor.intercept_

43996.88473520249

In [26]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x3_train, y3_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
regressor.coef_

array([-0.])

In [28]:
regressor.intercept_

25000.0

In [29]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x4_train, y4_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
regressor.coef_

array([-615.26479751])

In [31]:
regressor.intercept_

38987.53894080997

In [32]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x5_train, y5_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
regressor.coef_

array([0.])

In [34]:
regressor.intercept_

27428.571428571428